apiVersion: v1
kind: Namespace
metadata:
  name: bookworm-k8s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-bookworm-configmap
  namespace: bookworm-k8s
data:
  database_url: mongodb-bookworm-service
  mongo-root-username: user
  mongo-root-authdb: admin
  mongo-database: test
  auto-index-creation: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-bookworm-secret
  namespace: bookworm-k8s
type: Opaque
stringData:
  mongo-root-password: user
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-bookworm-service
  namespace: bookworm-k8s
spec:
  selector:
    app: mongodb-bookworm
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-bookworm-deployment
  namespace: bookworm-k8s
  labels:
    app: mongodb-bookworm
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: mongodb-bookworm
  template:
    metadata:
      labels:
        app: mongodb-bookworm
    spec:
      containers:
      - name: mongodb-bookworm
        image: mongo
        ports:
          - containerPort: 27017   
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongodb-bookworm-configmap
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-bookworm-secret
                key: mongo-root-password
        volumeMounts:
          - mountPath: bookworm/data/db
            name: mongo-bookworm-pv
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
      volumes:
        - name: mongo-bookworm-pv
          persistentVolumeClaim:
            claimName: mongo-bookworm-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-bookworm-pv
  namespace: bookworm-k8s
  labels:
    app: mongodb-bookworm
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /mnt/k8s/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-bookworm-pvc
  namespace: bookworm-k8s
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels: 
      app: mongodb-bookworm
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-bookworm-pv
  namespace: bookworm-k8s
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
   path: /data/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-bookworm-pvc
  namespace: bookworm-k8s
spec:
  storageClassName: ""
  resources:
    requests:
       storage: 50Gi
  volumeMode: Filesystem
  volumeName: redis-bookworm-pv
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  namespace: bookworm-k8s
  labels:
    app: redis-bookworm-deployment
  name: redis-bookworm-service
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    nodePort: 32666
  selector:
    app: redis-bookworm-deployment
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bookworm-k8s
  labels:
    app: redis-bookworm-deployment
  name: redis-bookworm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-bookworm-deployment
  template:
    metadata:
      labels:
        app: redis-bookworm-deployment
    spec:
      containers:
      - image: redis/redis-stack:latest
        name: redis
        command: ["redis-server"]
        args: ["--replica-announce-ip svc-redis-instance-1", "--requirepass root", 
        "--loadmodule /opt/redis-stack/lib/redisearch.so" , "--loadmodule /opt/redis-stack/lib/rejson.so",
        "--loadmodule /opt/redis-stack/lib/redistimeseries.so", "--loadmodule /opt/redis-stack/lib/redisbloom.so",
        "--save 10 1", "--appendonly yes", "--dir ./data"]
        volumeMounts:
        - name: "redis-bookworm-pvc"
          mountPath: "/data"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"           
      volumes:
      - name: "redis-bookworm-pvc"
        persistentVolumeClaim:
          claimName: "redis-bookworm-pvc"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookworm-configmap
  namespace: bookworm-k8s
data:
  security-jwt-clientid: BookWormClient
  security-jwt-accesstokenvaliditityseconds: "43200"
  security-jwt-authorizedgranttypes: password,authorization_code,refresh_token,client_credentials
  security-jwt-refreshtokenvalidityseconds: "2592000"
  redis-host: redis-bookworm-service.bookworm-k8s
  redis-port: "6379"
  redis-database: "0"
  redis-timeout: "60000"
  redis-pool-max-active: "8"
  redis-pool-max-idle: "8"
  redis-pool-min-idle: "0"
  admin-user-email: admin@bookworm.com
  system-user-email: system@bookworm.com
---
apiVersion: v1
kind: Secret
metadata:
  name: bookworm-secret
  namespace: bookworm-k8s
type: Opaque
stringData:
  security-jwt-clientsecret: secret
  security-jwt-signingkey: "123"
  redis-password: root
  admin-user-password: admin123
  system-user-password: system123
---
apiVersion: v1
kind: Service
metadata:
  name: bookworm-service
  namespace: bookworm-k8s
  labels:
     app: bookworm
spec:
  selector:
    app: bookworm
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32577
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookworm-deployment
  namespace: bookworm-k8s
  labels:
    app: bookworm
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: bookworm
  template:
    metadata:
      labels:
        app: bookworm
    spec:
      containers:
      - name: bookworm
        image: eftmk/bookworm:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8081
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /mnt/k8s/log
            name: bookworm-pv
        env:
          - name: CONFIG_MONGODB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongodb-bookworm-configmap
                key: mongo-root-username
          - name: CONFIG_MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-bookworm-secret
                key: mongo-root-password
          - name: CONFIG_MONGODB_AUTH_DB
            valueFrom:
              configMapKeyRef:
                name: mongodb-bookworm-configmap
                key: mongo-root-authdb
          - name: CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-bookworm-configmap
                key: database_url
          - name: CONFIG_MONGODB_AUTO_INDEX_CREATION
            valueFrom:
              configMapKeyRef:
                name: mongodb-bookworm-configmap
                key: auto-index-creation
          - name: CONFIG_SECURITY_JWT_CLIENTID
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: security-jwt-clientid
          - name: CONFIG_SECURITY_JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: bookworm-secret
                key: security-jwt-clientsecret
          - name: CONFIG_SECURITY_JWT_SIGNINGKEY
            valueFrom:
              secretKeyRef:
                name: bookworm-secret
                key: security-jwt-signingkey
          - name: CONFIG_SECURITY_JWT_ACCESSTOKEN_VALIDITYSECONDS
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: security-jwt-accesstokenvaliditityseconds
          - name: CONFIG_SECURITY_JWT_AUTHORIZED_GRANTTYPES
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: security-jwt-authorizedgranttypes
          - name: CONFIG_SECURITY_JWT_REFERSHTOKEN_VALIDITYSECONDS
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: security-jwt-refreshtokenvalidityseconds
          - name: CONFIG_REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: redis-host
          - name: CONFIG_REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: redis-port
          - name: CONFIG_REDIS_DATABASE
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: redis-database
          - name: CONFIG_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bookworm-secret
                key: redis-password
          - name: CONFIG_REDIS_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: redis-timeout
          - name: CONFIG_REDIS_POOL_MAX_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: redis-pool-max-active
          - name: CONFIG_REDIS_POOL_MAX_IDLE
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: redis-pool-max-idle
          - name: CONFIG_REDIS_POOL_MIN_IDLE
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: redis-pool-min-idle
          - name: CONFIG_ADMIN_USER_EMAIL
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: admin-user-email
          - name: CONFIG_ADMIN_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bookworm-secret
                key: admin-user-password
          - name: CONFIG_SYSTEM_USER_EMAIL
            valueFrom:
              configMapKeyRef:
                name: bookworm-configmap
                key: system-user-email
          - name: CONFIG_SYSTEM_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bookworm-secret
                key: system-user-password
      volumes:
        - name: bookworm-pv
          persistentVolumeClaim:
            claimName: bookworm-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookworm-pv
  namespace: bookworm-k8s
  labels:
    app: bookworm
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /mnt/k8s/log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookworm-pvc
  namespace: bookworm-k8s
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels: 
      app: bookworm